eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://102.219.178.237:8080/service-registry/eureka/eureka
  instance:
    hostname: 102.219.178.237
